// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqNsRlohdfNSp8PiORZoVvFLuC6esQeI',
    appId: '1:389345022584:web:dcd5431e19f97ae8a6138d',
    messagingSenderId: '389345022584',
    projectId: 'gogoleexample',
    authDomain: 'gogoleexample.firebaseapp.com',
    storageBucket: 'gogoleexample.firebasestorage.app',
    measurementId: 'G-87X9GH96GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz4h7OCup3Hc1-N5qbw04FMh8NcmUzE_Y',
    appId: '1:389345022584:android:2d3a4a739e7fa4f8a6138d',
    messagingSenderId: '389345022584',
    projectId: 'gogoleexample',
    storageBucket: 'gogoleexample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUCse34Wro_lJbCq5cFadc547u2SxQUZU',
    appId: '1:389345022584:ios:768f1a00ef11447ea6138d',
    messagingSenderId: '389345022584',
    projectId: 'gogoleexample',
    storageBucket: 'gogoleexample.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUCse34Wro_lJbCq5cFadc547u2SxQUZU',
    appId: '1:389345022584:ios:768f1a00ef11447ea6138d',
    messagingSenderId: '389345022584',
    projectId: 'gogoleexample',
    storageBucket: 'gogoleexample.firebasestorage.app',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqNsRlohdfNSp8PiORZoVvFLuC6esQeI',
    appId: '1:389345022584:web:d7fe383d9a214457a6138d',
    messagingSenderId: '389345022584',
    projectId: 'gogoleexample',
    authDomain: 'gogoleexample.firebaseapp.com',
    storageBucket: 'gogoleexample.firebasestorage.app',
    measurementId: 'G-8SY0DG2F8W',
  );
}
